name: Demo
on: [push, workflow_dispatch]
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Pull a Python image from Docker Hub
        run: docker pull python:3
      - name: Pull a Postgres image from Docker Hub
        run: docker pull postgres:11
