name: Demo
on: [push, workflow_dispatch]
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Pull an image from GHCR
        run: docker pull ghcr.io/microbiomedata/nmdc-runtime-fastapi:1.10.0
      - name: Pull an image from Docker Hub
        run: docker pull postgres:11
